services:
  db:
    image: '${DOCKER_IMAGE:-mysql:8.0.17}'
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - db:/var/lib/mysql
      - ./sql-init:/home/sql-init
      - ./scripts:/home/scripts
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}

      - MARIADB_DATABASE=${DATABASE}
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MARIADB_USER=${USER}
      - MARIADB_PASSWORD=${PASSWORD}
    env_file:
      - .env

volumes:
  db: {}
