services:
  db:
    image: '${DOCKER_MYSQL_IMAGE:-mysql:8.0.17}'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./sql-init:/home/sql-init
      - ./scripts:/home/scripts
      - ./my.cnf:/home/.my.cnf
    env_file:
      - .env

volumes:
  db: {}
